name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black pylint tqdm torch torchvision Pillow numpy requests
        pip install black
        pip install pylint
    - name: Formatting the code with black
      run: |
        black $(git ls-files '*.py')
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') --disable=R0913,C0116,R0903,E1101